name: 'deploy'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Setup
        with:
          version: '0.1.4'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          waypoint_server_address: 'waypoint.iamjambay.com:9701'
          waypoint_server_ui: 'waypoint.iamjambay.com:9702'
          waypoint_server_token: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
      - uses: ./
        name: Build
        with:
          operation: build
          version: '0.1.4'
          workspace: default
      - uses: ./
        name: Deploy
        with:
          operation: deploy
          version: '0.1.4'
          workspace: default
      - uses: ./
        name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          operation: release
          version: '0.1.4'
          workspace: default
